testAspShop/Models/Blog.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;


namespace testAspShop.Models;

public class Blog
{
    [Key]
    [BindNever]

    
    public int Id { get; set; }
    [Display(Name = "Введите название")]
    [Required(ErrorMessage = "Название обязательно для заполнения")]
    public string? Title { get; set; }
    [Display(Name = "Введите анонс")]
    [Required(ErrorMessage = "Анонс обязателен для заполнения")]
    public string? Annons { get; set; }
    [Display(Name = "Введите текст")]
    [Required(ErrorMessage = "Текст обязательно для заполнения")]
    public string? FullText { get; set; }

}

testAspShop/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using testAspShop.Data;
using testAspShop.Models;
using System.Collections;


namespace testAspShop.Controllers
{
    public class BlogController : Controller
    {

        private readonly AppDbContext _context;

        public BlogController(AppDbContext context) => _context = context;

        public IActionResult Index() // blog/
        {
            List<Blog> posts = _context.posts.ToList();
            return View(posts);
        }
       
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Blog post)
        {
            if (ModelState.IsValid)
            {
                _context.posts.Add(post);
                _context.SaveChanges();
                return Redirect("/blog");
            }
            return View();
        }

        [Route("blog/{id:int}/edit")]
        public ActionResult Edit(int id)
        {

            return View();

        }

        [HttpPost]
        [Route("blog/{id:int}/edit")]
        public IActionResult Edit(Blog editPost, int id)
        {
            if (ModelState.IsValid)
            {
                Blog? post = _context.posts.Find(id);
                post.Title = editPost.Title;
                post.Annons = editPost.Annons;
                post.FullText = editPost.FullText;
                _context.posts.Update(post);
                _context.SaveChanges();
                return Redirect("/blog");
            }
            return View();

        }
        
        [Route("blog/{id:int}/delete")]
        public IActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                Blog? post = _context.posts.Find(id) ?? new Blog();
                _context.posts.Remove(post);
                _context.SaveChanges();
            }
                return Redirect("/blog");
           



        }
    }
}

testAspShop/Views/Blog/Add.cshtml
@model Blog
 
@{
    ViewData["Title"] = "Добавление поста";
    ViewData["H1"] = "Добавление поста";
}

<div class="item order">
    <form method="post" asp-controller="Blog" asp-action="Add">
        <label asp-for="Title"> </label>
        <input asp-for="Title" />
        <span asp-validation-for="Title" class="error"> </span>

        <label asp-for="Annons"> </label>
        <input asp-for="Annons" />
        <span asp-validation-for="Annons" class="error"> </span>

        <label asp-for="FullText"> </label>
        <input asp-for="FullText" />
        <span asp-validation-for="FullText" class="error"> </span>
        <input type="submit" value="Добавить" />
    </form>
</div>

testAspShop/Views/Blog/Edit.cshtml
@model Blog
 
@{
    ViewData["Title"] = "Редактирование поста";
    ViewData["H1"] = "Редактирование поста";
}

<div class="item order">
    <form method="post" asp-controller="Blog" asp-action="Edit">
        <label asp-for="Title"> </label>
        <input asp-for="Title" />
        <span asp-validation-for="Title" class="error"> </span>

        <label asp-for="Annons"> </label>
        <input asp-for="Annons"/>
        <span asp-validation-for="Annons" class="error"> </span>

        <label asp-for="FullText"> </label>
        <input asp-for="FullText"/>
        <span asp-validation-for="FullText" class="error"> </span>
        <input type="submit" value="Изменить" />
    </form>
</div>

testAspShop/Views/Blog/Index.cshtml
@model List<Blog>

@{
    ViewData["Title"] = "Блог";
    ViewData["H1"] = "Блог сайта";
}



@foreach (var el in Model)
{
    <div class="item">
        <h1>@el.Title</h1>
        <p>@el.Annons</p>
        <a href="/blog/@el.Id/edit">Редактировать</a>
         <a href="/blog/@el.Id/delete">Удалить</a>

        
        
        

    </div>
}