testAspShop/Models/Order.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;

namespace testAspShop.Models
{
    public class Order
    {
        [BindNever]
        
        public int Id { get; set; }
        [Display(Name = "Введите имя")]
        [Required(ErrorMessage = "Имя обязательно для заполнения")]
        [StringLength(100, ErrorMessage ="Имя должно быть менее 30 символов")]
        public string Name { get; set; }
        [Display(Name = "Введите фамилию")]
        [Required(ErrorMessage = "Фамилия обязательно для заполнения")]
        [StringLength(100, ErrorMessage = "Фамилия должна быть менее 30 символов")]
        public string Surname { get; set; }
        [Display(Name = "Введите адрес")]
        [Required(ErrorMessage = "Адрес обязателен для заполнения")]
        [StringLength(100, ErrorMessage = "Адрес должен быть менее 30 символов")]
        public string Adress { get; set; }
        [Display(Name = "Введите номер телефона")]
        [Required(ErrorMessage = "Номер телефона обязателен для заполнения")]
        [StringLength(100, ErrorMessage = "Номер должен быть менее 30 символов")]
        [Phone]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }
        [Display(Name = "Введите Email")]
        [Required(ErrorMessage = "Email обязателен для заполнения")]
        [StringLength(100, ErrorMessage = "Email должен быть менее 30 символов")]
        [EmailAddress(ErrorMessage = "Вы ввели не Email")]
        public string Email { get; set; }

        [Required(ErrorMessage ="Ваша корзина пуста")]
        public string Cart { get; set; }
    }
}

testAspShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using testAspShop.Data;
using testAspShop.Models;
using CloudIpspSDK;
using CloudIpspSDK.Checkout;
namespace testAspShop.Controllers { 

    public class CartController : Controller
    {
        
        private readonly AppDbContext _context;


        public CartController( AppDbContext context)
        {
            _context = context;
           
        }

        public IActionResult Index()
        {
            List<Item> items = new List<Item>();
            
            String sessionItems = HttpContext.Session.GetString("items_id") ?? "";
            if(string.IsNullOrEmpty(sessionItems))
            {
                ViewBag.NoItems = "Нет товаров в корзине";
                return View(items);
            }

            int[] itemsId = Array.ConvertAll( sessionItems.Split(','), int.Parse);

            items = _context.items.Where(x => itemsId.Contains(x.Id)).ToList();

            
                ViewBag.Summary = items.Sum(x => x.Price);
            TempData["summary"] = ViewBag.Summary;

            
           
            return View(items);
        }

        public RedirectResult AddToCart(int id)
        {
            String idStr = id.ToString();
            String sessionItems = HttpContext.Session.GetString("items_id") ?? "";

            if (!sessionItems.Contains(idStr))
            {


                if (!sessionItems.Equals("")) sessionItems += "," + idStr;
                else sessionItems = idStr;
                HttpContext.Session.SetString("items_id", sessionItems);
            }
            return Redirect("/cart");
        }

        [HttpGet]
        public ActionResult Order()
        {
            ViewBag.sessionItems = HttpContext.Session.GetString("items_id") ?? "";
            return View();
        }

        [HttpPost]
        public IActionResult Order(Order order)
        {
            if (ModelState.IsValid)
            {
                _context.orders.Add(order); 
                _context.SaveChanges();
                Config.MerchantId = 1396424;
                Config.SecretKey = "test";

                var req = new CheckoutRequest
                {
                    order_id = Guid.NewGuid().ToString("N"),
                    amount = Convert.ToInt32(TempData["summary"]) * 100,
                    order_desc = "checkout json demo",
                    currency = "USD"
                };
                var resp = new Url().Post(req);
                string url = "/";
                if (resp.Error == null)
                {
                    url = resp.checkout_url;
                }
                

                    return Redirect(url);
            }
            ViewBag.sessionItems = HttpContext.Session.GetString("items_id") ?? "";
            return View();

        }
    }
}

testAspShop/Views/Cart/Index.cshtml
@model List<Item>

@{
    ViewData["Title"] = "Корзина";
    ViewData["H1"] = "Корзина";
}


<p>@ViewBag.NoItems</p>

@foreach(Item el in Model){
    <div class="order-item">
        <h1>@el.Name</h1>
        <p>Цена: @el.Price.ToString("c")</p>
    </div>
}
<div class="summary">

    @if(Model.Count > 0)
    {
    <p>Общая сумма: @ViewBag.Summary.ToString("c")</p>
    <a href="/cart/order">Оплатить</a>
        
    }

</div>

testAspShop/Views/Cart/Order.cshtml
@model Order

@{
    ViewData["Title"] = "Оформление заказа";
}
<h1>@ViewData["Title"]</h1>

<div class="item order">
    <form method="post" asp-controller="Cart" asp-action="Order">
        <label asp-for="Name"> </label>
        <input asp-for="Name" />
        <span asp-validation-for="Name" class="error"> </span>

        <label asp-for="Surname"> </label>
        <input asp-for="Surname" />
        <span asp-validation-for="Surname" class="error"> </span>

        <label asp-for="Adress"> </label>
        <input asp-for="Adress" />
        <span asp-validation-for="Adress" class="error"> </span>

        <label asp-for="PhoneNumber"> </label>
        <input asp-for="PhoneNumber" />
        <span asp-validation-for="PhoneNumber" class="error"> </span>

        <label asp-for="Email"> </label>
        <input asp-for="Email" />
        <span asp-validation-for="Email" class="error"> </span>

        <input asp-for="Cart" type="hidden" value="@ViewBag.sessionItems"/>
        <span asp-validation-for="Email" class="error"> </span>

        <input type="submit" value="Оплатить" />
    </form>
</div>